xmsgridtrace: xms::XmGridTraceImpl Class Reference
xms::XmGridTraceImpl Class Reference
XMS Namespace.
Public Member Functions
XmGridTraceImpl (BSHP< XmUGrid > a_ugrid)
Construct a new XmGridTrace using a UGrid.
double GetVectorMultiplier () const final
Returns the vector multiplier.
void SetVectorMultiplier (const double a_vectorMultiplier) final
Sets the vector multiplier.
double GetMaxTracingTime () const final
Returns the Max Tracing Time.
void SetMaxTracingTime (const double a_maxTracingTime) final
Sets the max tracing time.
double GetMaxTracingDistance () const final
Returns the Max Tracing Distance.
void SetMaxTracingDistance (const double a_maxTracingDistance) final
Sets the max tracing distance.
double GetMinDeltaTime () const final
Returns the min delta time.
void SetMinDeltaTime (const double a_minDeltaTime) final
Sets the min delta time.
double GetMaxChangeDistance () const final
Returns the max change distance.
void SetMaxChangeDistance (const double a_maxChangeDistance) final
Sets the max change distance.
double GetMaxChangeVelocity () const final
Returns the max change in velcoity.
void SetMaxChangeVelocity (const double a_maxChangeVelocity) final
Sets the max change in velocity.
double GetMaxChangeDirectionInRadians () const final
Returns the max change in direction in radians.
void SetMaxChangeDirectionInRadians (const double a_maxChangeDirection) final
Sets the max change in direction in radians.
void AddGridScalarsAtTime (const VecPt3d &a_scalars, DataLocationEnum a_scalarLoc, xms::DynBitset &a_activity, DataLocationEnum a_activityLoc, double a_time) final
Assigns velocity vectors to each point or cell for a time step, keeping the previous step, and dropping the one before that for a maximum of two time steps.
void TracePoint (const Pt3d &a_pt, const double &a_ptTime, VecPt3d &a_outTrace, VecDbl &a_outTimes) final
Runs the Grid Trace for a point.
std::string GetExitMessage () final
returns a message describing what caused trace to exit
Public Member Functions inherited from xms::XmGridTrace
virtual ~XmGridTrace ()
Deconstruct XmGridTrace.
Private Member Functions
bool GetVectorAtLocationAndTime (const xms::Pt3d &a_pt, double a_currentTime, xms::Pt3d &a_data) const
Returns the velocity scalar for a given point and time.
Private Attributes
BSHP< XmUGrid > m_ugrid
double m_vectorMultiplier
double m_maxTracingTime
double m_maxTracingDistance
double m_minDeltaTime
double m_maxChangeDistance
double m_maxChangeVelocity
double m_maxChangeDirectionInRadians
BSHP< XmUGrid2dDataExtractor > m_extractor1x
BSHP< XmUGrid2dDataExtractor > m_extractor1y
double m_time1
BSHP< XmUGrid2dDataExtractor > m_extractor2x
BSHP< XmUGrid2dDataExtractor > m_extractor2y
double m_time2
double m_distTraveled
std::string m_exitMessage
Additional Inherited Members
Static Public Member Functions inherited from xms::XmGridTrace
static BSHP< XmGridTrace > New (BSHP< XmUGrid > a_ugrid)
Construct XmGridTrace for a UGrid.
Detailed Description
XMS Namespace.
Implementation for XmGridTrace.
Implementation for XmUGrid2dDataExtractor
Definition at line 58 of file XmGridTrace.cpp.
Constructor & Destructor Documentation
xms::XmGridTraceImpl::XmGridTraceImpl (BSHP< XmUGrid > a_ugrid)
Construct a new XmGridTrace using a UGrid.
Parameters
[in] a_ugrid The UGrid to construct a grid trace for
Definition at line 119 of file XmGridTrace.cpp.
Member Function Documentation
void xms::XmGridTraceImpl::AddGridScalarsAtTime (const VecPt3d & a_scalars, DataLocationEnum a_scalarLoc, xms::DynBitset & a_activity, DataLocationEnum a_activityLoc, double a_time) final virtual
Assigns velocity vectors to each point or cell for a time step, keeping the previous step, and dropping the one before that for a maximum of two time steps.
Parameters
[in] a_scalars The velocity vectors
[in] a_scalarLoc Whether the vectors are assigned to cells or points
[in] a_activity Whether each cell or point is active
[in] a_activityLoc Whether the activities are assigned to cells or points
[in] a_time The time of the scalars
Implements xms::XmGridTrace.
Definition at line 269 of file XmGridTrace.cpp.
bool xms::XmGridTraceImpl::GetVectorAtLocationAndTime (const xms::Pt3d & a_pt, double a_currentTime, xms::Pt3d & a_data) const private
Returns the velocity scalar for a given point and time.
Parameters
[in] a_pt The point
[in] a_currentTime The time at extraction
[out] a_data the resultant velocity scalar
Definition at line 504 of file XmGridTrace.cpp.
References xmlog::error, xmlog::warning, xms::Pt3< T >::x, XM_LOG, XM_ZERO_TOL, and xms::Pt3< T >::y.
Referenced by TracePoint().
void xms::XmGridTraceImpl::SetMaxChangeDirectionInRadians (const double a_maxChangeDirection) final virtual
Sets the max change in direction in radians.
Parameters
[in] a_maxChangeVelocity the new max change in direction in radians
Implements xms::XmGridTrace.
Definition at line 244 of file XmGridTrace.cpp.
References XM_PI.
void xms::XmGridTraceImpl::SetMaxChangeDistance (const double a_maxChangeDistance) final virtual
Sets the max change distance.
Parameters
[in] a_maxChangeDistance the new max change distance
Implements xms::XmGridTrace.
Definition at line 214 of file XmGridTrace.cpp.
void xms::XmGridTraceImpl::SetMaxChangeVelocity (const double a_maxChangeVelocity) final virtual
Sets the max change in velocity.
Parameters
[in] a_maxChangeVelocity the new max change in velocity
Implements xms::XmGridTrace.
Definition at line 229 of file XmGridTrace.cpp.
void xms::XmGridTraceImpl::SetMaxTracingDistance (const double a_maxTracingDistance) final virtual
Sets the max tracing distance.
Parameters
[in] a_maxTracingDistance the new max tracing distance
Implements xms::XmGridTrace.
Definition at line 177 of file XmGridTrace.cpp.
void xms::XmGridTraceImpl::SetMaxTracingTime (const double a_maxTracingTime) final virtual
Sets the max tracing time.
Parameters
[in] a_maxTracingTime the new max tracing time
Implements xms::XmGridTrace.
Definition at line 162 of file XmGridTrace.cpp.
void xms::XmGridTraceImpl::SetMinDeltaTime (const double a_minDeltaTime) final virtual
Sets the min delta time.
Parameters
[in] a_minDeltaTime the new min delta time
Implements xms::XmGridTrace.
Definition at line 192 of file XmGridTrace.cpp.
References XM_ZERO_TOL.
void xms::XmGridTraceImpl::SetVectorMultiplier (const double a_vectorMultiplier) final virtual
Sets the vector multiplier.
Parameters
[in] a_vectorMultiplier the new vector multiplier
Implements xms::XmGridTrace.
Definition at line 147 of file XmGridTrace.cpp.
void xms::XmGridTraceImpl::TracePoint (const Pt3d & a_pt, const double & a_ptTime, VecPt3d & a_outTrace, VecDbl & a_outTimes) final virtual
Runs the Grid Trace for a point.
Parameters
[in] a_pt The starting point of the trace
[in] a_ptTime The starting time of the trace
[out] a_outTrace the resultant positions at each step
[out] a_outTimes the resultant times at each step
Implements xms::XmGridTrace.
Definition at line 304 of file XmGridTrace.cpp.
References xms::EQ_TOL(), xmlog::error, GetVectorAtLocationAndTime(), xms::Mdist(), xms::Pt3< T >::x, XM_LOG, XM_NODATA, XM_ZERO_TOL, and xms::Pt3< T >::y.
The documentation for this class was generated from the following file:
/home/travis/build/Aquaveo/xmsgridtrace/xmsgridtrace/gridtrace/XmGridTrace.cpp